name: Build Metamod for ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            make \
            cmake \
            libc6-dev \
            libc6-dev-arm64-cross \
            build-essential

      - name: Configure build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
          cd ..

      - name: Build
        run: |
          cd build
          make -j$(nproc)
          cd ..

      - name: Check output folders
        run: ls -R build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: metamod-arm64
          path: build/**/*.so
