name: Build Metamod-R ARM64

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix apt sources.list to use jammy instead of noble
        run: sudo sed -i 's/noble/jammy/g' /etc/apt/sources.list

      - name: Update apt and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metamod-r-so-files
          path: build/*/*.so
