name: Build Metamod-R for ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu make

      - name: Build with build.sh
        run: |
          chmod +x build.sh
          ./build.sh --compiler=gcc-aarch64-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: metamod-arm64
          path: build/*/*.so
